name: device_frame_plus
description: Mockups for common devices.
version: 1.2.2
repository: https://github.com/mjablecnik/device_frame_plus

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.2.0'

dependencies:
  freezed_annotation: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  json_serializable: ^6.0.1
  freezed: ^2.5.2
  flutter_lints: ^4.0.0
